# Generated by Django 2.2.6 on 2019-12-26 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DjangoApp', '0002_auto_20191209_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='country',
            new_name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default='Enter', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default='Enter', max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='h_no',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Enter', max_length=50)),
                ('last_name', models.CharField(default='Enter', max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('h_no', models.CharField(max_length=1000)),
                ('street', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('landmark', models.CharField(max_length=50, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DjangoApp.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
